### ISSUE TITLE
Allow use of default foundry color scheme

### ISSUE THREAD

**Issue by Dr-Turtle** [fvtt-fria-ligan/morkborg-foundry-vtt#102]
I prefer the default color scheme of foundry to the schemes available in the options for this system, I think an additional option to switch to fvtt's default color scheme would be a good addition.

**Comment by mcglincy** [comment]
@Dr-Turtle how's this?

![Screen Shot 2021-05-04 at 9 17 45 AM](https://user-images.githubusercontent.com/189172/117017881-985b9c80-acb9-11eb-8064-477f69fe50b1.png)

**Comment by Dr-Turtle** [comment]
Looks good! Thank you! I look forward to using it!

**Comment by mcglincy** [comment]
cool! this will ship with the next 0.3.7 release.
