### ISSUE TITLE
Broken template paths 

### ISSUE THREAD

**Issue by maqloner** [fvtt-fria-ligan/morkborg-foundry-vtt#105]
In the latest version, some templates are broken. I've found at least 2 so far.

NOENT: no such file or directory
'E:\FoundryVTT_AppData\Data\systems\morkborg\templates\party-initiative-roll-card.html'
E:\FoundryVTT_AppData\Data\systems\morkborg\templates\dialog\add-item-dialog.html'

**Comment by mcglincy** [comment]
Thanks for the bug report; I'll take a look.

**Comment by mcglincy** [comment]
Fixed those two paths, tested locally, and pushed a new 0.3.8 system version. Thanks!

**Comment by mcglincy** [comment]
@maqloner I spot-checked the other template paths in the system, but let me know if you notice any other breakage. thanks!

**Comment by maqloner** [comment]
Ok thank you, that was fast.
