### ISSUE TITLE
Add tables from pages 39-43 for "Create Scvm"

### ISSUE THREAD

**Issue by ScottMaclure** [fvtt-fria-ligan/morkborg-foundry-vtt#107]
Tables:
- Terrible Traits
- Broken Bodies
- Bad Habits
- Troubling Tales

Can generate as a paragraph of text and append to the Obituary. Something like:

> You are [[terrible_trait]], [[broken_body]], and [[bad_habit]]. Rumour has it [[troubling_tale]].

Could edit the start of each random value so the sentence flows nicely for every item.

**Comment by mcglincy** [comment]
Unfortunately, I didn't get permission from the MÖRK BORG authors to use that content from the book. I can follow up with them to ask.

**Comment by mcglincy** [comment]
Got permission to include traits, bodies, and habits, and merged those with my own Terribler Traits, Brokener Bodies, and Badder Habits for some uber-lists of 56 items each.

These are now included in the Create Scvm / Scvmfactory character generation.

Troubling Tales begins to intersect with GM adventure plot or backstory, so I'm going to punt on including that for now.

These changes are live in the latest 1.0.4 version. Thanks!
