### ISSUE TITLE
Add RollTables for Arcane Catastrophes to Compendium

### ISSUE THREAD

**Issue by Lim-Dul** [fvtt-fria-ligan/morkborg-foundry-vtt#120]
This would include rolling on them when using scrolls.
I believe this would require permission from the Mörk Borg authors as they contain flavorful and potentially copyrighted descriptions (vide Refva).

I already prepared some RollTables for that and shared them privately, waiting for a reply as to the possibility of including them.

**Comment by mcglincy** [comment]
Talked with Nohr today on discord and got permission to include the catastrophes.

**Comment by mcglincy** [comment]
Implemented in upcoming 1.3.0.
