### ISSUE TITLE
Add link to GitHub repo in system list

### ISSUE THREAD

**Issue by Lim-Dul** [fvtt-fria-ligan/morkborg-foundry-vtt#121]
Currently no link to the GitHub repo is provided in the system list entry.
It would be nice to have it handy to always check the latest changes.

![image](https://user-images.githubusercontent.com/428324/145688717-94ffc630-d6f2-4c63-843e-9a0ba31f3f87.png)

vs e.g. Into the Odd (and most others)

![image](https://user-images.githubusercontent.com/428324/145688761-69c5532c-6bef-4209-a449-c446ead1a6d2.png)

**Comment by mcglincy** [comment]
Fixed in 1.3.0. (I needed to set the url field in system.json.)
