### ISSUE TITLE
Arcane Catastrophes table references a world table and not the correct compendium entry

### ISSUE THREAD

**Issue by maqloner** [fvtt-fria-ligan/morkborg-foundry-vtt#139]
The result 19 on the Arcane Catastrophes reference the world document "To Leave Cube Violet" which don't exist if you don't import the compendium into the world.

It should references the item "To Leave Cube-Violet" from the compendium "morkborg.random-scrolls"

**Comment by mcglincy** [comment]
Fixed in 1.10.1.
