### ISSUE TITLE
Update "image frame" with readable font colors. 

### ISSUE THREAD

**Issue by r-valyar** [fvtt-fria-ligan/morkborg-foundry-vtt#14]
Update "image frame" with readable font colors. 

![image](https://user-images.githubusercontent.com/63558984/105558191-a5f6a300-5d16-11eb-9831-e6a0bae9c810.png)

**Comment by mcglincy** [comment]
Thanks for the report! Maybe not the final style, but here's a CSS change to fix the readability:

![Screen Shot 2021-01-22 at 5 38 54 PM](https://user-images.githubusercontent.com/189172/105560223-da4b6e80-5cd8-11eb-84f9-133624b2d385.png)

**Comment by mcglincy** [comment]
CSS fix committed, will show up in next release (0.1.6).
