### ISSUE TITLE
[enhancement] Force reload of application when color/font schemes are changed and settings saved

### ISSUE THREAD

**Issue by r-valyar** [fvtt-fria-ligan/morkborg-foundry-vtt#140]
The purpose of this enhancement is to automatically initiate application reload when color/font schemes are changed and settings saved

Today I have to manually reload for the new theme to take effect, a behavior that differs from other theme implementations in FVTT.

**Comment by mcglincy** [comment]
Fixed in upcoming 1.11.0.
