### ISSUE TITLE
Ammo item type doesn't drag-drop into containers

### ISSUE THREAD

**Issue by mcglincy** [fvtt-fria-ligan/morkborg-foundry-vtt#147]

**Comment by hibikutek** [comment]
I just tried to replicate this issue, but from what I can tell it is working with Bolt, Arrow, and Sling Stone, and both from the compendium directly to the container, and from within the 'treasures' tab.  

Maybe this issue can be closed?

**Comment by mcglincy** [comment]
nice, thanks for testing. Closing.
