### ISSUE TITLE
Make Powers per day text interactive like Omens per day

### ISSUE THREAD

**Issue by Lim-Dul** [fvtt-fria-ligan/morkborg-foundry-vtt#148]
*Expected Result*
Clicking the _Powers per day_ info text triggers a macro resetting usage similar to the _Omens per rest_ info text.

*Actual Result*
Hovering over the _Powers per day_ info text highlights it as if it was an interactive element but clicking it does nothing. The only way to reset power usage is per the rest button or manually. This is inconsistent with how a similar functionality for Omens works, where you can click the info text.
![image](https://user-images.githubusercontent.com/428324/178591061-b7f36025-a908-4498-8269-2ecb2464b642.png)
![image](https://user-images.githubusercontent.com/428324/178591086-00d6a239-c433-4e24-a1f3-8ec2e0c8ac0a.png)

*Steps to Reproduce*
1. Open a player's character sheet
2. Click on the "Powers" tab
3. Hover over the "PRE+d4 times per day" info text and attempt clicking on it

**Comment by mcglincy** [comment]
There's a rollable span in character-sheet.html:
<span class="rule-text rollable powers-per-day-text">{{localize "MB.PowersPerDayText"}}</span>

but character-sheet.js activateListeners() doesn't actually hook anything to it. There is already a _onPowersPerDayRoll() method defined, so should be just adding the click handler.

**Comment by Lim-Dul** [comment]
Confirmed fixed in v1.14.0.
