### ISSUE TITLE
Follower max HP keeps resetting

### ISSUE THREAD

**Issue by Zankoas** [fvtt-fria-ligan/morkborg-foundry-vtt#153]
A small but slightly annoying bug where follower HP resets.

Steps to replicate:

1. Import a follower, say a Monkey, from the compendium
2. Open the follower's character sheet
3. Change the max HP
4. Change the current HP
5. See that the max HP has reset back to default

Since some followers have rolled HP, this makes it rather difficult to track their HP.

Versions:

- Foundry version 10, build 286
- MÖRK BORG version 2.0.1
- No modules active

Of course anything else you need to replicate just let me know. Hope this helps!

**Comment by mcglincy** [comment]
Thanks for the bug report! Looks like a borked field name broken during the changes for v10 support. Fixed in 2.0.2.

**Comment by Zankoas** [comment]
That was amazingly fast, thanks so much!
