### ISSUE TITLE
Items macros

### ISSUE THREAD

**Issue by rklos** [fvtt-fria-ligan/morkborg-foundry-vtt#162]
Hi,
two years ago you've implemented macros support for items: https://github.com/fvtt-fria-ligan/morkborg-foundry-vtt/issues/46.
Now, dragging items (for example weapons) to macro toolbar works only for "toggleDocumentSheet" - it opens the document with item description instead of roll for an attack (also for armour).

In my opinion dragging items to macro toolbar should trigger roll for it.

**Comment by mcglincy** [comment]
I agree, and IIRC the weapon macro originally triggered attack roll and the armor defense roll... so it must have gotten broken along the way. I'll look at fixing.

**Comment by mcglincy** [comment]
Fixed in upcoming release 2.4.0.
