### ISSUE TITLE
Issue with "Dice Tray" module

### ISSUE THREAD

**Issue by r-valyar** [fvtt-fria-ligan/morkborg-foundry-vtt#17]
I know that "Dice Tray" is third party module, but only in the system the tray has unreadable dice buttons. Low priority

![image](https://user-images.githubusercontent.com/63558984/105576142-74fb8a00-5d79-11eb-871a-cedb11b7ed02.png)

**Comment by mcglincy** [comment]
Yeah, I think in our attempts to style the UI and chat -- and my followup attempts to fix various things -- we made some CSS classes overly broad or global. We should avoid having to explicitly fix style for every third party module, which is not a sustainable solution :) (And, I use Dice Tray in my other games, too!) @eeyun

**Comment by mcglincy** [comment]
Default Dice Tray style (as seen in dnd5e system): 

![Screen Shot 2021-01-24 at 7 55 14 PM](https://user-images.githubusercontent.com/189172/105652123-2daaf180-5e7e-11eb-8851-b7327c9810de.png)

**Comment by mcglincy** [comment]
The offending style setting is our broad setting of .window-app .window-content background (to black), which clash's with dicetray's button color (black).

**Comment by mcglincy** [comment]
Fixed in upcoming 1.9.0.
