### ISSUE TITLE
Assets missing - Dead god's prophet

### ISSUE THREAD

**Issue by zxaos** [fvtt-fria-ligan/morkborg-foundry-vtt#172]
Using just this base module, the compendium item for dead god's prophet is missing all art. It seems to want to load it out of `modules/morkborg-cult-feretory/assets/dead-gods-prophet/` but that path doesn't exist.

**Comment by mcglincy** [comment]
Thanks for the bug report! I pushed a new 3.2.1 release with the paths fixed.

No comment what "modules/morkborg-cult-feretory" might be! 😉
