### ISSUE TITLE
[suggestion] Create "rollable" attacks & defence for Creatures/Followers

### ISSUE THREAD

**Issue by r-valyar** [fvtt-fria-ligan/morkborg-foundry-vtt#18]
It seems at the moment that armor and attacks of a creature cannot be rolled, they are just text that show to the GM what is the dice to roll for their damage. But I think it will be amazing if there is way to "create" attack and damage by putting the dice type and have the nice reporting in the chat that we have for Players.

**Comment by r-valyar** [comment]
Ignore that, I forgot that in this game NPCs don't roll, just players :)

**Comment by mcglincy** [comment]
Closing. 

FWIW, I just filed a different issue for something related, which is to allow entering the DR/SG for the attack or defense roll, so we can do better logic or presentation of the roll result: #21
