### ISSUE TITLE
Module management font is not readable

### ISSUE THREAD

**Issue by r-valyar** [fvtt-fria-ligan/morkborg-foundry-vtt#5]
Module management panel is not readable. Change of font color is required to something more readable :)
![image](https://user-images.githubusercontent.com/63558984/104934677-1918b600-59b3-11eb-9d5f-626eabbcde3a.png)

**Comment by mcglincy** [comment]
Workaround fix in morkborg.css:

#module-management .package-list .package-title, #module-management .package-list .package-metadata, #module-management .package-list .package-description {
  color: white;
}

**Comment by mcglincy** [comment]
Fixed in v0.1.1
