### ISSUE TITLE
Ranged attack rolls should use Presence and not Agility

### ISSUE THREAD

**Issue by maqloner** [fvtt-fria-ligan/morkborg-foundry-vtt#76]
Currently, the game system use the agility score when you do an attack roll for a ranged attack, based on the rule book it should be presence.

**Comment by mcglincy** [comment]
Doh, you are right!

And here's the incorrect code:
    // ranged weapons use agility; melee weapons use strength
    const ability = isRanged ? 'agility' : 'strength';

Thanks for the report; I'll fix.

**Comment by mcglincy** [comment]
Fixed, and pushed a new 0.2.8 version with the fix.

Thanks @maqloner !
