### ISSUE TITLE
Palms of the Southern Gate typo

### ISSUE THREAD

**Issue by hruhek** [fvtt-fria-ligan/morkborg-foundry-vtt#83]
There is a typo in the Palms Open the Southern Gate spell description (Equipment - Scrolls).
<img width="565" alt="Screenshot 2021-04-14 at 17 52 03" src="https://user-images.githubusercontent.com/39823032/114743357-e6315480-9d4c-11eb-8923-a6c7ba648408.png">

**Comment by mcglincy** [comment]
Thanks for the proofreading!

Fixed, will ship in 0.2.11.
